# Usa la imagen oficial de MariaDB
FROM mariadb:latest

# Variables de entorno para inicializar la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=biblioteca

# Archivo SQL para crear el esquema y datos iniciales
COPY /sql/init.sql /docker-entrypoint-initdb.d/

# Exponer el puerto por defecto de MariaDB
EXPOSE 3306

#06/12/24 Si bien se construye un contenedor con maria db no se le instala sql por lo que los comandos ejecutados no funcionan correctamente